// Simple script to load .env and generate config.env.js for browser
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
let envVars = {};

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const lines = envContent.split('\n');
  
  lines.forEach(line => {
    line = line.trim();
    if (line && !line.startsWith('#')) {
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length > 0) {
        const value = valueParts.join('=').trim().replace(/^["']|["']$/g, '');
        envVars[key.trim()] = value;
      }
    }
  });
}

const configContent = `// Auto-generated from .env file
// DO NOT EDIT - Generated by load-env.js

if (typeof window !== 'undefined') {
  window.ENV_CONFIG = {
    SUPABASE_URL: '${envVars.SUPABASE_URL || ''}',
    SUPABASE_ANON_KEY: '${envVars.SUPABASE_ANON_KEY || ''}',
    OPENROUTER_API_KEY: '${envVars.OPENROUTER_API_KEY || ''}',
    OPENROUTER_MODEL: '${envVars.OPENROUTER_MODEL || 'tngtech/deepseek-r1t2-chimera:free'}',
    SITE_URL: '${envVars.SITE_URL || 'https://tranquilmind.app'}'
  };
}
`;

fs.writeFileSync(path.join(__dirname, 'config.env.js'), configContent);
console.log('✅ Generated config.env.js from .env file');

